name: Azure CLI Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Azure CLI command
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az --version
            # Add your other az commands here

